WGSErpApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WGSErpApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WGSErpApp/Controllers/ProductionPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArabErp.Web.Controllers
{
    public class ProductionPlanController : Controller
    {
        public ActionResult ProductionIndex()
        {
            return View();
        }

        public ActionResult AdminIndex()
        {
            return View();
        }

        public ActionResult PurchaseIndex()
        {
            return View();
        }        


        public ActionResult SalesIndex()
        {
            return View();
        }      

        public ActionResult FinancialAccountsIndex()
        {
            return View();
        } 
        public ActionResult HRMSIndex()
        {
            return View();
        } 
        // GET: ProductionPlan
        public ActionResult CreateProductionPlan()
        {
            return View();
        }

        public ActionResult CreateProductionPlanAdd()
        {
            return View();
        }
        public ActionResult ProductionPlanEdit()
        {
            return View();
        }
        public ActionResult PurchaseIndent()
        {
            return View();
        }
        public ActionResult PreviousPurchaseIndent()
        {
            return View();
        }
        public ActionResult PurchaseIndentApproval()
        {
            return View();
        }
        public ActionResult PendingPurchaseIndent()
        {
            return View();
        }
        public ActionResult PurchaseOrder()
        {
            return View();
        }
        public ActionResult PreviousPurchaseOrder()
        {
            return View();
        }
        public ActionResult PurchaseOrderApproval()
        {
            return View();
        }
        public ActionResult PendingPurchaseOrder()
        {
            return View();
        }
        public ActionResult MaterialPlanningReport()
        {
            return View();
        }
        public ActionResult ProductionPlanMPR()
        {
            return View();
        }
        public ActionResult StockOrderMPR()
        {
            return View();
        }
        public ActionResult CustomerOrderMPR()
        {
            return View();
        }
        public ActionResult ProductionScheduleMPR()
        {
            return View();
        }
        public ActionResult GRN()
        {
            return View();
        }
        public ActionResult ProductionOrder()
        {
            return View();
        }
        public ActionResult GoodsIssue()
        {
            return View();
        }
        public ActionResult ConfirmProduction()
        {
            return View();
        }
        public ActionResult PendingGoodsIssue()
        {
            return View();
        }
        public ActionResult ReceiveFinishedGoods()
        {
            return View();
        }
        public ActionResult ProductionOrderReport()
        {
            return View();
        }
        public ActionResult StockRequirementReport()
        {
            return View();
        }
        public ActionResult CreateProductLine()
        {
            return View();
        }
        public ActionResult ProductGroup()
        {
            return View();
        }
        public ActionResult ProductSubGroup()
        {
            return View();
        }
        public ActionResult ProductionOrderRelease()
        {
            return View();
        }
        public ActionResult PlanedOrder()
        {
            return View();
        }
        public ActionResult ConvertPlannedOrdertoPurReq()
        {
            return View();
        }
        public ActionResult ConvertPlannedOrdertoProductionOrder()
        {
            return View();
        }
        public ActionResult PendingProduction()
        {
            return View();
        }
        public ActionResult PendingReceiveProductInventory()
        {
            return View();
        }
        public ActionResult ConvertProductionPlanttoplannedorder()
        {
            return View();
        }
        public ActionResult ProductionPlantoProductionSchedule()
        {
            return View();
        }
        public ActionResult ProductionSchedule()
        {
            return View();
        }
        public ActionResult CustomerOrder()
        {
            return View();
        }
        public ActionResult ConvertCustomerOrderProductionSchedule()
        {
            return View();
        }
        public ActionResult ConvertCustomerOrderPurIndent()
        {
            return View();
        }
        public ActionResult ConvertProductionPlanPurIndent()
        {
            return View();
        }
        public ActionResult PreviousCustomerOrder()
        {
            return View();
        }
        public ActionResult PendingCustomerOrder()
        {
            return View();
        }
        public ActionResult SupplierCategory()
        {
            return View();
        }
        public ActionResult RawMaterial()
        {
            return View();
        }
        public ActionResult ComponentOverView()
        {
            return View();
        }
        public ActionResult PreviousReceiveProductInventory()
        {
            return View();
        }
        public ActionResult PreviousIssueMaterialProductionOrder()
        {
            return View();
        }
        public ActionResult PreviousProductionOrder()
        {
            return View();
        }
        public ActionResult SalesInvoice()
        {
            return View();
        }
        public ActionResult PendingSalesInvoice()
        {
            return View();
        }
        public ActionResult DeliveryChallan()
        {
            return View();
        }
        public ActionResult PendingDeliveryChallan()
        {
            return View();
        }
        public ActionResult PreviousGRN()
        {
            return View();
        }
        //public ActionResult CreateProductLineAdd()
        //{
        //    return View();
        //}
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Month()
        {
            return View();
        }
        public ActionResult FinancialYear()
        {
            return View();
        }
        public ActionResult Product()
        {
            return View();
        }
        public ActionResult Unit()
        {
            return View();
        }
        public ActionResult Item()
        {
            return View();
        }
        public ActionResult Supplier()
        {
            return View();
        }
        public ActionResult Plant()
        {
            return View();
        }
        public ActionResult Sale()
        {
            return View();
        }
        public ActionResult Layout()
        {
            return View();
        }
    }
}

WGSErpApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About ERP";
}
@*<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@

<p>We understand and appreciate the many challenges the system users face regarding accuracy, complexity, quality, delivery and deadline. We will support those users and their deadlines to the best of our ability. Not only with the common off the shelf items, but also diverse and custom items made especially for their requirement or particular project
‘We have a proven track record in this aspect and the clients whom we have been servicing for years together are the visible example of that.’</p>

WGSErpApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>IHits Technologies </h2>
<h3>ERP for Production</h3>

<address>
    45/2024E, 2nd Floor, Sabari Associates, P J Cochin-12,<br />
     PJ Antony Rd, Pachalam, Kochi, Kerala 682012<br />

    <abbr title="Phone">P:</abbr>
    0484 606 0141
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@ihitsindia.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">sales@ihitsindia.com</a>
</address>

WGSErpApp/Views/Home/Index.cshtml

@{
   // ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="body">

    <div class="container">
 
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-5">
                    </div>
                <div class="col-md-7">
                    <div class="col-md-4 module">
                        <a href="@Url.Action("AdminIndex","ProductionPlan")"><img src="~/Images/admin1.png" /></a>
                    </div>
                    <div class="col-md-4 module">
                        <a href="@Url.Action("ProductionIndex", "ProductionPlan")"><img src="~/Images/production.png" /></a>
                    </div>
                    <div class="col-md-4 module">
                        <a href="@Url.Action("PurchaseIndex","ProductionPlan")"><img src="~/Images/Purchase.png" /></a>
                    </div>
                    <div class="col-md-4 module">
                        <a href="@Url.Action("SalesIndex","ProductionPlan")"><img src="~/Images/Sales.png" /></a>
                    </div>
                    <div class="col-md-4 module">
                        <a href="@Url.Action("FinancialAccountsIndex","ProductionPlan")"><img src="~/Images/fa.png" /></a>
                    </div>
                    <div class="col-md-4 module">
                        <a href="@Url.Action("HRMSIndex","ProductionPlan")"><img src="~/Images/hrms.png" /></a>
                    </div>
                    </div>
                </div>
        </div>

    </div>


</body>